# Generated by Django 5.2.11 on 2026-07-23 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_formation', '0002_inscription_formation_unique_numero_inscription_etablissement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationAutoPilot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('fuseau_horaire', models.CharField(default='Africa/Bamako', max_length=50)),
                ('duree_lecon_defaut_minutes', models.PositiveIntegerField(default=60)),
                ('verifier_expiration_documents', models.BooleanField(default=True)),
                ('permettre_examen_sans_heures_minimum', models.BooleanField(default=False)),
                ('prefixe_numero_dossier', models.CharField(default='AE', max_length=10)),
                ('prefixe_matricule_moniteur', models.CharField(default='MON', max_length=10)),
                ('score_maximum_evaluation', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('delai_annulation_lecon_heures', models.PositiveIntegerField(default=24)),
                ('apercu_disponibilite_jours', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_autopilot', to='django_formation.etablissement')),
            ],
            options={
                'verbose_name': 'Configuration AutoPilot',
                'verbose_name_plural': 'Configurations AutoPilot',
                'db_table': 'autopilot_configuration',
            },
        ),
        migrations.CreateModel(
            name='JournalAuditAutoPilot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('categorie', models.CharField(default='GENERAL', max_length=50)),
                ('entite_type', models.CharField(blank=True, max_length=100)),
                ('entite_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_autopilot', to='django_formation.etablissement')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_autopilot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit AutoPilot",
                'verbose_name_plural': "Journaux d'audit AutoPilot",
                'db_table': 'autopilot_journal_audit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['etablissement', '-created_at'], name='autopilot_j_etablis_f677c8_idx'), models.Index(fields=['action'], name='autopilot_j_action_79eaa6_idx'), models.Index(fields=['categorie'], name='autopilot_j_categor_4b945b_idx'), models.Index(fields=['entite_type', 'entite_id'], name='autopilot_j_entite__17f502_idx')],
            },
        ),
    ]
