from django.urls import path
from django_formation.api import views

app_name = "formation"

urlpatterns = [
    path("etablissements/", views.etablissement_list_create, name="etablissement-list"),
    path("etablissements/<uuid:pk>/", views.etablissement_detail, name="etablissement-detail"),
    path("etablissements/<uuid:pk>/activer/", views.etablissement_activer, name="etablissement-activer"),
    path("etablissements/<uuid:pk>/desactiver/", views.etablissement_desactiver, name="etablissement-desactiver"),
    path("etablissements/<uuid:pk>/membres/", views.membre_list_create, name="membre-list"),
    path("membres/<uuid:pk>/", views.membre_detail, name="membre-detail"),
    path("apprenants/", views.apprenant_list_create, name="apprenant-list"),
    path("apprenants/<uuid:pk>/", views.apprenant_detail, name="apprenant-detail"),
    path("apprenants/<uuid:pk>/activer/", views.apprenant_activer, name="apprenant-activer"),
    path("apprenants/<uuid:pk>/desactiver/", views.apprenant_desactiver, name="apprenant-desactiver"),
    path("apprenants/<uuid:pk>/archiver/", views.apprenant_archiver, name="apprenant-archiver"),
    path("apprenants/<uuid:pk>/inscriptions/", views.apprenant_inscriptions, name="apprenant-inscriptions"),
    path("formations/", views.formation_list_create, name="formation-list"),
    path("formations/<uuid:pk>/", views.formation_detail, name="formation-detail"),
    path("formations/<uuid:pk>/publier/", views.formation_publier, name="formation-publier"),
    path("formations/<uuid:pk>/suspendre/", views.formation_suspendre, name="formation-suspendre"),
    path("formations/<uuid:pk>/reactiver/", views.formation_reactiver, name="formation-reactiver"),
    path("formations/<uuid:pk>/archiver/", views.formation_archiver, name="formation-archiver"),
    path("formations/<uuid:pk>/sessions/", views.formation_sessions, name="formation-sessions"),
    path("sessions/", views.session_list_create, name="session-list"),
    path("sessions/<uuid:pk>/", views.session_detail, name="session-detail"),
    path("sessions/<uuid:pk>/ouvrir-inscriptions/", views.session_ouvrir_inscriptions, name="session-ouvrir-inscriptions"),
    path("sessions/<uuid:pk>/fermer-inscriptions/", views.session_fermer_inscriptions, name="session-fermer-inscriptions"),
    path("sessions/<uuid:pk>/demarrer/", views.session_demarrer, name="session-demarrer"),
    path("sessions/<uuid:pk>/terminer/", views.session_terminer, name="session-terminer"),
    path("sessions/<uuid:pk>/annuler/", views.session_annuler, name="session-annuler"),
    path("sessions/<uuid:pk>/inscriptions/", views.session_inscriptions, name="session-inscriptions"),
    path("sessions/<uuid:pk>/statistiques/", views.session_statistiques, name="session-statistiques"),
    path("inscriptions/", views.inscription_list_create, name="inscription-list"),
    path("inscriptions/<uuid:pk>/", views.inscription_detail, name="inscription-detail"),
    path("inscriptions/<uuid:pk>/mettre-en-attente/", views.inscription_mettre_en_attente, name="inscription-mettre-en-attente"),
    path("inscriptions/<uuid:pk>/confirmer/", views.inscription_confirmer, name="inscription-confirmer"),
    path("inscriptions/<uuid:pk>/refuser/", views.inscription_refuser, name="inscription-refuser"),
    path("inscriptions/<uuid:pk>/annuler/", views.inscription_annuler, name="inscription-annuler"),
    path("inscriptions/<uuid:pk>/demarrer/", views.inscription_demarrer, name="inscription-demarrer"),
    path("inscriptions/<uuid:pk>/abandonner/", views.inscription_abandonner, name="inscription-abandonner"),
    path("inscriptions/<uuid:pk>/terminer/", views.inscription_terminer, name="inscription-terminer"),
    path("inscriptions/<uuid:pk>/historique/", views.inscription_historique, name="inscription-historique"),
]
