# Generated by Django 5.2.11 on 2026-07-23 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('code', models.SlugField(unique=True, verbose_name='Code')),
                ('raison_sociale', models.CharField(blank=True, max_length=255, verbose_name='Raison sociale')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='Mali', max_length=100, verbose_name='Pays')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['code'], name='django_form_code_53bb47_idx'), models.Index(fields=['actif'], name='django_form_actif_1dd0c3_idx'), models.Index(fields=['nom'], name='django_form_nom_4a9a83_idx')],
            },
        ),
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=20, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200, verbose_name='Contact urgence - Nom')),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=30, verbose_name='Contact urgence - Téléphone')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_apprenant_formation', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apprenants', to='django_formation.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Apprenant',
                'verbose_name_plural': 'Apprenants',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('objectifs', models.TextField(blank=True, verbose_name='Objectifs')),
                ('duree_heures', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (heures)')),
                ('duree_jours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (jours)')),
                ('tarif_indicatif', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Tarif indicatif')),
                ('devise', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiée'), ('SUSPENDUE', 'Suspendue'), ('ARCHIVEE', 'Archivée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formations', to='django_formation.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, verbose_name='Numéro')),
                ('date_inscription', models.DateField(verbose_name="Date d'inscription")),
                ('statut', models.CharField(choices=[('PREINSCRITE', 'Préinscrite'), ('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée'), ('EN_COURS', 'En cours'), ('ABANDONNEE', 'Abandonnée'), ('TERMINEE', 'Terminée')], default='PREINSCRITE', max_length=25, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif de refus')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='django_formation.apprenant', verbose_name='Apprenant')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='django_formation.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutInscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancien_statut', models.CharField(blank=True, max_length=25, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(max_length=25, verbose_name='Nouveau statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='django_formation.inscription', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': "Historique de statut d'inscription",
                'verbose_name_plural': "Historiques de statut d'inscription",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembreEtablissement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PROPRIETAIRE', 'Propriétaire'), ('ADMINISTRATEUR', 'Administrateur'), ('RESPONSABLE', 'Responsable de formation'), ('AGENT_INSCRIPTION', "Agent d'inscription"), ('LECTEUR', 'Lecteur')], max_length=30, verbose_name='Rôle')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='django_formation.etablissement', verbose_name='Établissement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions_formation', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Membre d'établissement",
                'verbose_name_plural': "Membres d'établissement",
            },
        ),
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_ouverture_inscriptions', models.DateField(blank=True, null=True, verbose_name="Date d'ouverture des inscriptions")),
                ('date_fermeture_inscriptions', models.DateField(blank=True, null=True, verbose_name='Date de fermeture des inscriptions')),
                ('capacite', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité')),
                ('tarif', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Tarif')),
                ('devise', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('INSCRIPTIONS_OUVERTES', 'Inscriptions ouvertes'), ('INSCRIPTIONS_FERMEES', 'Inscriptions fermées'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=25, verbose_name='Statut')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_formation', to='django_formation.etablissement', verbose_name='Établissement')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='django_formation.formation', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Session de formation',
                'verbose_name_plural': 'Sessions de formation',
            },
        ),
        migrations.AddField(
            model_name='inscription',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='django_formation.sessionformation', verbose_name='Session'),
        ),
        migrations.AddConstraint(
            model_name='apprenant',
            constraint=models.UniqueConstraint(fields=('etablissement', 'matricule'), name='formation_unique_matricule_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.UniqueConstraint(fields=('etablissement', 'code'), name='formation_unique_code_formation_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='membreetablissement',
            constraint=models.UniqueConstraint(fields=('etablissement', 'utilisateur'), name='formation_unique_membre_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='sessionformation',
            constraint=models.UniqueConstraint(fields=('etablissement', 'code'), name='formation_unique_code_session_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('apprenant', 'session'), name='formation_unique_apprenant_session'),
        ),
    ]
