# Generated by Django 5.2.11 on 2026-07-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_formation', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('etablissement', 'numero'), name='formation_unique_numero_inscription_etablissement'),
        ),
    ]
